name: Deploy

on:
  push:
    branches:
      - React-Sample-Deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you want

      - name: Install dependencies
        working-directory: ./client  # Change the working directory to 'client'
        uses: bahmutov/npm-install@v1

      - name: Build project
        working-directory: ./client  # Change the working directory to 'client'
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./client/dist  # Adjust path if necessary

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/React-Sample-Deploy'  # Check against the correct branch

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./client/dist  # Adjust path if necessary

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist  # Ensure this points to the correct output directory
